---
- name: Gather information about installed software on Windows
  hosts: windows
  gather_facts: yes
  become: true  # Run as administrator
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Get installed programs from the registry (HKEY_LOCAL_MACHINE)
      win_registry:
        path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
        name: ""
        state: list
      register: installed_software_registry

    - name: Display installed software from registry
      debug:
        var: installed_software_registry
