---
- name: Install TightVNC and set VNC authentication password
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install TightVNC using Chocolatey
      win_chocolatey:
        name: tightvnc
        state: present

    - name: Set the TightVNC password
      ansible.windows.win_registry:
        path: "HKCU:\\Software\\TightVNC\\Server"
        name: "Password"
        data: "F0rs4f3gu4rding"
        type: "String"

    - name: Enable TightVNC server (if necessary)
      win_service:
        name: "TightVNC"
        state: started
        start_mode: auto
