---
- name: Install MySQL Workbench 8.0.41 on MacBook Pro 14-inch
  hosts: macbook
  become: yes
  tasks:
    - name: Install MySQL Workbench
      homebrew:
        name: mysqlworkbench
        state: present
