---
- name: Install PDF Gear on Windows 11
  hosts: windows  # The target host/group in your inventory
  become: true    # Run as administrator
  tasks:
    - name: Download PDF Gear installer
      win_get_url:
        url: https://downloadfiles.pdfgear.com/releases/windows/pdfgear_setup_v2.1.12.exe
        dest: C:\Temp\pdfgear_setup_v2.1.12.exe

    - name: Install PDF Gear
      win_command: C:\Temp\pdfgear_setup_v2.1.12.exe /S  # The /S flag runs the installer silently
      args:
        creates: C:\Program Files\pdfgear_setup_v2.1.12.exe  # Check if PDF Gear is already installed
